apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oz627swsu-nodejs
  janus-idp.io/tekton: oz627swsu-nodejs
  backstage.io/kubernetes-id: oz627swsu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oz627swsu-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
