apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oz627swsu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oz627swsu-nodejs 
  name: oz627swsu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oz627swsu-nodejs 
